# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckedoutBookPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckeoutWindow(object):
    def setupUi(self, CheckeoutWindow):
        CheckeoutWindow.setObjectName("CheckeoutWindow")
        CheckeoutWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CheckeoutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 751, 451))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(245)
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(660, 530, 89, 25))
        self.button_back.setObjectName("button_back")
        CheckeoutWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CheckeoutWindow)
        self.statusbar.setObjectName("statusbar")
        CheckeoutWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CheckeoutWindow)
        QtCore.QMetaObject.connectSlotsByName(CheckeoutWindow)

    def retranslateUi(self, CheckeoutWindow):
        _translate = QtCore.QCoreApplication.translate
        CheckeoutWindow.setWindowTitle(_translate("CheckeoutWindow", "MainWindow"))
        self.label.setText(_translate("CheckeoutWindow", "Checked Out Book List"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CheckeoutWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CheckeoutWindow", "isbn"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CheckeoutWindow", "Date"))
        self.button_back.setText(_translate("CheckeoutWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CheckeoutWindow = QtWidgets.QMainWindow()
    ui = Ui_CheckeoutWindow()
    ui.setupUi(CheckeoutWindow)
    CheckeoutWindow.show()
    sys.exit(app.exec_())

