# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckinApprovalPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckinApprovalWindow(object):
    def setupUi(self, CheckinApprovalWindow):
        CheckinApprovalWindow.setObjectName("CheckinApprovalWindow")
        CheckinApprovalWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CheckinApprovalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_accept = QtWidgets.QPushButton(self.centralwidget)
        self.button_accept.setGeometry(QtCore.QRect(580, 140, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_accept.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../tmp/mozilla_sim0/icons8-ok-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_accept.setIcon(icon)
        self.button_accept.setIconSize(QtCore.QSize(75, 75))
        self.button_accept.setObjectName("button_accept")
        self.button_reject = QtWidgets.QPushButton(self.centralwidget)
        self.button_reject.setGeometry(QtCore.QRect(580, 310, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_reject.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../tmp/mozilla_sim0/icons8-cancel-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_reject.setIcon(icon1)
        self.button_reject.setIconSize(QtCore.QSize(75, 75))
        self.button_reject.setObjectName("button_reject")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 50, 501, 451))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(153)
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(670, 530, 89, 25))
        self.button_back.setObjectName("button_back")
        CheckinApprovalWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CheckinApprovalWindow)
        self.statusbar.setObjectName("statusbar")
        CheckinApprovalWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CheckinApprovalWindow)
        QtCore.QMetaObject.connectSlotsByName(CheckinApprovalWindow)

    def retranslateUi(self, CheckinApprovalWindow):
        _translate = QtCore.QCoreApplication.translate
        CheckinApprovalWindow.setWindowTitle(_translate("CheckinApprovalWindow", "MainWindow"))
        self.button_accept.setText(_translate("CheckinApprovalWindow", "Accept"))
        self.button_reject.setText(_translate("CheckinApprovalWindow", "Reject"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CheckinApprovalWindow", "student id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CheckinApprovalWindow", "book isbn"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CheckinApprovalWindow", "Date"))
        self.button_back.setText(_translate("CheckinApprovalWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CheckinApprovalWindow = QtWidgets.QMainWindow()
    ui = Ui_CheckinApprovalWindow()
    ui.setupUi(CheckinApprovalWindow)
    CheckinApprovalWindow.show()
    sys.exit(app.exec_())

