# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeacherAprovalPAge.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherAprovalWindow(object):
    def setupUi(self, TeacherAprovalWindow):
        TeacherAprovalWindow.setObjectName("TeacherAprovalWindow")
        TeacherAprovalWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TeacherAprovalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 50, 461, 451))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(500)
        self.button_accept = QtWidgets.QPushButton(self.centralwidget)
        self.button_accept.setGeometry(QtCore.QRect(560, 150, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_accept.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../tmp/mozilla_sim0/icons8-ok-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_accept.setIcon(icon)
        self.button_accept.setIconSize(QtCore.QSize(50, 50))
        self.button_accept.setObjectName("button_accept")
        self.button_reject = QtWidgets.QPushButton(self.centralwidget)
        self.button_reject.setGeometry(QtCore.QRect(560, 300, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_reject.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../tmp/mozilla_sim0/icons8-cancel-26.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_reject.setIcon(icon1)
        self.button_reject.setIconSize(QtCore.QSize(50, 50))
        self.button_reject.setObjectName("button_reject")
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setGeometry(QtCore.QRect(660, 520, 89, 25))
        self.button_back.setObjectName("button_back")
        TeacherAprovalWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TeacherAprovalWindow)
        self.statusbar.setObjectName("statusbar")
        TeacherAprovalWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TeacherAprovalWindow)
        QtCore.QMetaObject.connectSlotsByName(TeacherAprovalWindow)

    def retranslateUi(self, TeacherAprovalWindow):
        _translate = QtCore.QCoreApplication.translate
        TeacherAprovalWindow.setWindowTitle(_translate("TeacherAprovalWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TeacherAprovalWindow", "id"))
        self.button_accept.setText(_translate("TeacherAprovalWindow", "Accept"))
        self.button_reject.setText(_translate("TeacherAprovalWindow", "Reject"))
        self.button_back.setText(_translate("TeacherAprovalWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeacherAprovalWindow = QtWidgets.QMainWindow()
    ui = Ui_TeacherAprovalWindow()
    ui.setupUi(TeacherAprovalWindow)
    TeacherAprovalWindow.show()
    sys.exit(app.exec_())

